apiVersion: v1                    # API version for core Kubernetes objects
kind: Pod                         # We are creating a Pod
metadata:
  name: empty-dir-demo            # Name of the Pod
  namespace: default              # Namespace where the Pod will run

spec:
  containers:
  # ---------------------- Container 1 ----------------------
  - name: nginx                   # First container inside the Pod
    image: nginx                  # Using nginx image
    volumeMounts:
    - mountPath: /var/log/nginx   # Mount the shared volume to store NGINX logs
      name: nginx-logs            # Name of the volume

  # ---------------------- Container 2 ----------------------
  - name: almalinux               # Second container inside the same Pod
    image: almalinux:9            # Using Almalinux image
    command: ["sleep", "1000"]    # Keep the container running for testing
    volumeMounts:
    - mountPath: /mnt/nginx-log   # Mount same shared directory in this container
      name: nginx-logs            # Same volume as nginx container
      readOnly: true              # Mounted as read-only (can ONLY view nginx logs)

  # ---------------------- Volume Definition ----------------
  volumes:
  - name: nginx-logs              # Defining a volume named nginx-logs
    emptyDir:                     # emptyDir is a temporary storage volume
      sizeLimit: 100Mi            # Limit the size to 100Mi (optional)
