apiVersion: v1
kind: PersistentVolume               # Creating a PersistentVolume (PV)
metadata:
  name: ebs-static                   # Name of the PV
spec:
  accessModes:
    - ReadWriteOnce                  # EBS can be mounted to ONLY one node at a time (RWO)

  persistentVolumeReclaimPolicy: Retain   # Keep EBS volume even after PVC deletion

  capacity:
    storage: 15Gi                    # Size of the EBS volume

  csi:
    driver: ebs.csi.aws.com          # AWS EBS CSI driver
    fsType: ext4                     # File system format
    volumeHandle: vol-0fc2f30bedd19f958   # Actual AWS EBS volume ID (must already exist)
---
apiVersion: v1
kind: PersistentVolumeClaim          # PVC requested by the user/app
metadata:
  name: ebs-static                   # PVC name (will bind to PV of same name)
spec:
  storageClassName: ""               # Must be empty to avoid default StorageClass binding
  volumeName: ebs-static             # Explicitly bind to this PV
  accessModes:
    - ReadWriteOnce                  # Must match the PV access mode
  resources:
    requests:
      storage: 15Gi                  # PVC requests same size as PV
---
apiVersion: v1
kind: Pod                            # Pod that will use the PVC
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html               # Volume name to mount inside container
      mountPath: /usr/share/nginx/html   # NGINX default web directory
  volumes:
  - name: nginx-html                 # Declaring the volume for the pod
    persistentVolumeClaim:           # Use PVC as the storage source
      claimName: ebs-static          # PVC name to bind to
