apiVersion: v1                    # PV uses core API group
kind: PersistentVolume            # Creating a PersistentVolume (PV)
metadata:
  name: ebs-static                # Name of the PV

spec:
  accessModes:
    - ReadWriteOnce               # Only one node can mount this EBS volume at a time

  persistentVolumeReclaimPolicy: Retain   # Correct field name (case-sensitive)

  capacity:
    storage: 15Gi                 # Size of the volume

  csi:
    driver: ebs.csi.aws.com       # AWS EBS CSI driver
    fsType: ext4                  # Filesystem type
    volumeHandle: vol-0fc2f30bedd19f958   # Actual AWS EBS Volume ID
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
