apiVersion: v1
kind: PersistentVolume               # Creating a PersistentVolume (PV)
metadata:
  name: ebs-static                   # Name of the PV
spec:
  accessModes:
    - ReadWriteOnce                  # EBS can be mounted to ONLY one node at a time (RWO)

  persistentVolumeReclaimPolicy: Retain   # Keep EBS volume even after PVC deletion

  capacity:
    storage: 15Gi                    # Size of the EBS volume

  csi:
    driver: ebs.csi.aws.com          # AWS EBS CSI driver
    fsType: ext4                     # File system type
    volumeHandle: vol-0fc2f30bedd19f958   # AWS EBS volume ID (must already exist)
---
apiVersion: v1
kind: PersistentVolumeClaim          # PVC requested by the user/app
metadata:
  name: ebs-static                   # PVC name (binds to PV with same name)
spec:
  storageClassName: ""               # Required → prevents default StorageClass
  volumeName: ebs-static             # Force PVC to bind to this PV
  accessModes:
    - ReadWriteOnce                  # Must match PV's RWO
  resources:
    requests:
      storage: 15Gi                  # Request same storage size as PV
---
apiVersion: v1
kind: Pod                            # Pod that uses the PVC
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html               # Volume name inside pod
      mountPath: /usr/share/nginx/html   # NGINX default web directory

  nodeSelector:                      # Ensures pod runs in same AZ as EBS volume
    topology.kubernetes.io/zone: us-east-1f

  volumes:
  - name: nginx-html
    persistentVolumeClaim:           # Mount the PVC
      claimName: ebs-static          # Use the PVC created above
