
#StorageClass created by admin
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
reclaimPolicy: Retain #default value is delete we need to change
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer