apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkins.url: "http://joindevops/build/job/5"
    imageregistory: "http://hub.docker.com"
spec:
  containers:
  - name: nginx
    image: nginx